---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MIME-Lite
no_index:
  directory:
    - t
    - inc
requires:
  Email::Date::Format: '1.000'
  File::Basename: '0'
  File::Spec: '0'
  MIME::Base64: '0'
  MIME::QuotedPrint: '0'
  MIME::Types: '1.28'
  Mail::Address: '1.62'
resources:
  repository: http://github.com/rjbs/MIME-Lite
version: '3.033'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
